services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hn\McpServer\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Explicitly register command controllers
  Hn\McpServer\Command\McpServerCommand:
    tags:
      - name: 'console.command'
        command: 'mcp:server'
        description: 'Starts an MCP (Model Context Protocol) server using stdio transport'
        
  Hn\McpServer\Command\McpTestCommand:
    tags:
      - name: 'console.command'
        command: 'mcp:test'
        description: 'Test MCP tools directly without starting a server'
        
  Hn\McpServer\Command\OAuthManageCommand:
    tags:
      - name: 'console.command'
        command: 'mcp:oauth'
        description: 'Manage OAuth tokens for MCP server'
        
  # Make ToolRegistry public for eID access
  Hn\McpServer\MCP\ToolRegistry:
    public: true
    
  # Make WorkspaceContextService public 
  Hn\McpServer\Service\WorkspaceContextService:
    public: true
    
  # Make OAuthService public for eID access
  Hn\McpServer\Service\OAuthService:
    public: true
    
  # Explicitly configure the module controller
  Hn\McpServer\Controller\McpServerModuleController:
    public: true
    arguments:
      $moduleTemplateFactory: '@TYPO3\CMS\Backend\Template\ModuleTemplateFactory'
      $toolRegistry: '@Hn\McpServer\MCP\ToolRegistry'
      $pageRenderer: '@TYPO3\CMS\Core\Page\PageRenderer'
      $oauthService: '@Hn\McpServer\Service\OAuthService'
