services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hn\McpServer\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Explicitly register command controllers
  Hn\McpServer\Command\McpServerCommand:
    tags:
      - name: 'console.command'
        command: 'mcp:server'
        description: 'Starts an MCP (Model Context Protocol) server using stdio transport'
        
  Hn\McpServer\Command\McpTestCommand:
    tags:
      - name: 'console.command'
        command: 'mcp:test'
        description: 'Test MCP tools directly without starting a server'
        
  Hn\McpServer\Command\GenerateTokenCommand:
    tags:
      - name: 'console.command'
        command: 'mcp:generate-token'
        description: 'Generate MCP access token for backend users'
        
  # Make ToolRegistry public for eID access
  Hn\McpServer\MCP\ToolRegistry:
    public: true
